### ISSUE TITLE
Error when compiling example in README

### ISSUE THREAD

**Issue by tonyfleck76** [yglukhov/nimx#109]
When compiling the example, I get an error on ttf_ttf.c, saying that it cannot find memory.h.

`ttf_ttf.c:701:23: fatal error: memory.h: No such file or directory.`
`#include <memory.h>`

Is there any solution to this? Or a memory.h file that I need to just copy and paste into the nimcache directory?

**Comment by yglukhov** [comment]
Thats strange. What os/toolchain are you using?

**Comment by tonyfleck76** [comment]
Windows and minGW. Also thanks for the rapid reply!

**Comment by yglukhov** [comment]
I would bet something is wrong with your mingw installation, because `memory.h` should come along with it. As a workaround, just comment out the line `#include <memory.h>` in your `NIMBLE_PACKAGES/ttf/ttf.nim`. I think it should work that way.

**Comment by tonyfleck76** [comment]
Alright, that does appear to have fixed the issue, thanks! I may have to look into that minGW installation though and make sure that nothing is missing there.

**Comment by yglukhov** [comment]
Anytime. Closing this for now. If you find that it's normal for mingw to not have `memory.h`, feel free to file a pull request to ttf ;)
