### ISSUE TITLE
main.nim won't build

### ISSUE THREAD

**Issue by kirbyfan64** [yglukhov/nimx#13]
I get:

```
[Linking]
nimcache/nimx_main.o: In function `main':
nimcache/nimx_main.c:(.text+0x4940): multiple definition of `main'
nimcache/nimx_linkage_details.o:nimcache/nimx_linkage_details.c:(.text+0x0): first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed
```

`main` seems to be defined in both `nimx/linkage_details.nim` and `main.nim`.

**Comment by yglukhov** [comment]
Please try building with --noMain argument to nim. Unfortunately SDL requires it's own main.

**Comment by kirbyfan64** [comment]
@yglukhov Yeah...that fixed it... \*self-slap*

**Comment by apense** [comment]
FYI on windows it seems to be the opposite. Compiling with ``--noMain`` fails with ``undefined reference to `WinMain'``
