### ISSUE TITLE
errors on compiling on windows

### ISSUE THREAD

**Issue by roose** [yglukhov/nimx#136]
win10, nim x64

`.nimble\pkgs\nimx-0.1\nimx\font.nim(244, 26) Error: type mismatch: got (stbtt_fontinfo, ptr font_type, int literal(0))
but expected one of:
proc stbtt_InitFont(info: var stbtt_fontinfo; data: font_type; fontstart: cint): cint`

if I delete `ptr` from `stbtt_InitFont(fontinfo, cast[ptr font_type](rawData.cstring), 0)`:

`.nimble\pkgs\nimx-0.1\nimx\view.nim(369, 14) template/generic instantiation from here
.nimble\pkgs\nimx-0.1\nimx\class_registry.nim(49, 25) template/generic instantiation from here
.nimble\pkgs\nimx-0.1\nimx\class_registry.nim(31, 32) template/generic instantiation from here
.nimble\pkgs\variant-0.1.0\variant.nim(29, 46) Error: no generic parameters allowed for ref`

**Comment by yglukhov** [comment]
Please make sure you're using the latest versions of everything.
```
nimble install -y https://github.com/yglukhov/ttf
nimble install -y variant
```
Also use latest nim devel.

**Comment by roose** [comment]
Thanks, works on latest nim devel
