### ISSUE TITLE
Multi-line text widget

### ISSUE THREAD

**Issue by ephja** [yglukhov/nimx#140]
Is there one yet? I couldn't find one.

Would it be best to use a table in the meantime?

**Comment by yglukhov** [comment]
Currently there's no such thing, but it is in near plans. I don't think tables would be handy for this. I would rather extend (and then contribute! 😉 ) existing `TextField`.

**Comment by ephja** [comment]
Do you think it's a good idea to extend it with scrolling and line breaking? Several things can be re-used though. What do you think of Qt's approach of inheriting from a scroll bar widget?

**Comment by yglukhov** [comment]
@ephja, I would rather use composition and reuse existing ScrollView to embed the TextField within:
```nim
let textField = TextField.new(someRect)
textField.multiline = true
textField.autoresizingMask = { afFlexibleWidth, afFlexibleHeight }
let scrollView = newScrollView(textField) # Embedding into ScrollView
```

As for line breaking, eventually we will definitely need it, but I can't tell you do it or not. If you're into contributing, I can only thank you ( and maybe criticize just a bit ;) ).

**Comment by yglukhov** [comment]
Please, check out latest nimx samples and `formatted_text` module.
