### ISSUE TITLE
Error running main nimx example code.

### ISSUE THREAD

**Issue by TomAshley303** [yglukhov/nimx#149]
I followed the instructions but when I compiled/ran the example I get:

~/.nimble/pkgs/nimx-0.1/nimx/view.nim(400, 14) template/generic instantiation from here
~/.nimble/pkgs/nimx-0.1/nimx/class_registry.nim(49, 25) template/generic instantiation from here
~/.nimble/pkgs/nimx-0.1/nimx/class_registry.nim(31, 32) template/generic instantiation from here
~/.nimble/pkgs/variant-0.1.0/variant.nim(29, 46) Error: no generic parameters allowed for ref

**Comment by TomAshley303** [comment]
My bad. Didn't notice your note about needing the latest dev version of nim so I just replaced the current version with the git repo/dev branch.

**Comment by yglukhov** [comment]
So it works now, right?
