### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by GraydenH** [yglukhov/nimx#175]
Is this being worked on? I managed to figure out the place to start is probably to make a GraphicsContext from context.nim, other than that there is little go off of from there.

**Comment by yglukhov** [comment]
The documentation is planned, though not a priority. Please feel free to contribute ;). As for starting, you can with the sample in the `README`, and then go through nimx samples. You don't need `GraphicsContext` unless you want some custom drawing.

**Comment by AjBreidenbach** [comment]
Hi, I think the documentation needs to get done even if it isn't a priority.  I would be willing to contribute if no one else wants to do it, but I don't know enough about nimx yet. In any case I'd rather the next person not have to learn by trial and error.

**Comment by ieatnerds** [comment]
I agree. Needs to be done. This is such a nice library but without any kind of proper documentation it is excessively difficult to use.
