### ISSUE TITLE
Tried font '\Windows\Fonts\Arial.ttf' with no luck

### ISSUE THREAD

**Issue by xland** [yglukhov/nimx#18]
on windows 10
Hint:  [Link]
Hint: operation successful (46607 lines compiled; 1.846 sec total; 51.522MB; Debug Build) [SuccessX]
Shader compile log: WARNING: 0:1: '' :  #version directive missing

Shader compile log: WARNING: 0:6: '' :  #version directive missing

Shader compile log: WARNING: 0:1: '' :  #version directive missing

Shader compile log: WARNING: 0:6: '' :  #version directive missing

Tried font '\Windows\Fonts\Arial.ttf' with no luck
WARNING: Could not create system font
Error: execution of an external program failed

**Comment by xland** [comment]
#19

**Comment by yglukhov** [comment]
Ahh, you probably have you windows installation not in `C:\Windows` or something. For a quick fix, correct `fontSearchPaths` in `font.nim`. Also PRs are welcome, to find Font dir in runtime ;)

**Comment by yglukhov** [comment]
Fixed by #19, right? =)
