### ISSUE TITLE
accessing local variables periodically

### ISSUE THREAD

**Issue by ephja** [yglukhov/nimx#182]
If indeed it's not possible, then some ways to deal with this includes:

* Allowing the engine to be updated without exposing implementation details of targets, thus allowing timers to be bypassed
* Associating an object with a timer, that is passed to the callback

**Comment by yglukhov** [comment]
Looks like you wanted to post this elsewhere, because I could not understand a thing.

**Comment by ephja** [comment]
No, this is the correct repo 😆

What I meant was, is there a way to execute user code periodically, which accesses some state that is not declared globally? The callback passed to `timers.setInterval` neither takes a parameter nor is it a closure. The first bullet point might be the wrong approach, because I'm not sure how that would translate to browser applications for example.

Does it make sense now?

**Comment by yglukhov** [comment]
`timers.setInterval` takes a closure as argument.
```nim
var i = 0
setInterval do():
  inc i
  echo i
```

**Comment by ephja** [comment]
I thought it was necessary to annotate the parameter with the `closure` pragma.
Won't the function where `setInterval` is invoked go out of scope before the event loop is executed?

**Comment by yglukhov** [comment]
> I thought it was necessary to annotate the parameter with the closure pragma.

Proc args are closures by default.

> Won't the function where setInterval is invoked go out of scope before the event loop is executed?

Sorry, but I don't understand the question again. `setInterval` schedules a timer in runloop. Why would scope matter?

**Comment by ephja** [comment]
nevermind
