### ISSUE TITLE
Static linking

### ISSUE THREAD

**Issue by Immortalin** [yglukhov/nimx#185]
Any plans for static linking?

**Comment by yglukhov** [comment]
Static linking to what?

**Comment by Immortalin** [comment]
static linking against libsdl2

**Comment by yglukhov** [comment]
It is supported on behalf of nim. If you're using nimx naketools, its already done for ios and android. Otherwise, tell nim to not generate dyn glue with `--dynlibOverride:SDL2` flag, and tell it to link properly with `--passL:-lSDL2` or whatever you need.

**Comment by yglukhov** [comment]
Closing. Please reopen if you still think theres an issue here.
