### ISSUE TITLE
What are the requirements again?

### ISSUE THREAD

**Issue by NookSF** [yglukhov/nimx#195]
Just `SDL2` or `SDL2` using the OpenGL backend? 

Trying to run against SDL2 + GLES backend fails:
````
Could not create program: 0
````

**Comment by yglukhov** [comment]
I suppose it should work with SDL2 + GL or GLES. Could you provide more details about your environment and steps to reproduce?

**Comment by NookSF** [comment]
Sure, the only pertinent difference between a working setup (libSDL2 + OpenGL 2.0) is the fact this `libSDL2` had been built  with `--disable-video-opengl` meaning it only supports `x11` and `opengles` (ES 1.1 and 2.0) backends.

**Comment by NookSF** [comment]
Switching between the two versions was done via `LD_LIBRARY_PATH`

**Comment by yglukhov** [comment]
I really don't know what to say. The message you're observing is telling that `glCreateProgram` failed, but glGetError returns 0. Have you previously managed to create shaders with your SDL+GLES lib?

**Comment by NookSF** [comment]
I believe I have, see [here](https://github.com/mgerhardy/caveexpress/search?utf8=%E2%9C%93&q=shaders) for example, which runs just fine in this setup.

**Comment by yglukhov** [comment]
Please try the following:
```nim
import sdl2
import opengl

if sdl2.init(INIT_VIDEO) != SdlSuccess:
    doAssert(false, "init")

if glSetAttribute(SDL_GL_STENCIL_SIZE, 8) != 0:
    doAssert(false, "glSetAttribute")

let w = createWindow(nil, 50, 50, 800, 600, SDL_WINDOW_OPENGL or SDL_WINDOW_RESIZABLE or SDL_WINDOW_ALLOW_HIGHDPI)
doAssert(not w.isNil, "createWindow")

discard glSetAttribute(SDL_GL_SHARE_WITH_CURRENT_CONTEXT, 1)

let c = w.glCreateContext()
doAssert(not c.isNil, "glCreateContext")

discard glMakeCurrent(w, c)

when not defined(ios) and not defined(android) and not defined(js) and not defined(emscripten):
    loadExtensions()

let p = glCreateProgram()
doAssert(p != 0, "glCreateProgram")

echo "Everything is cool!"
```
```sh
nim c -r test.nim
```

**Comment by NookSF** [comment]
OK, but this has to use the working OpenGL setup (the other copy copy of `libSDL`):

````
 ./test
Everything is cool!
````

**Comment by NookSF** [comment]
My only suggestion is `OpenGL ES 2` is not a drop-in replacement for `OpenGL 2`, so it's possible we're simply dealing with OpenGL specific stuff here. In that case my question is answered and some porting is required.

**Comment by yglukhov** [comment]
@NookSF, if this snippet doesnt work with SDL+GLES, you might want to have a look at how Nim's [opengl](https://github.com/nim-lang/opengl) works. Maybe you could correct its behavior as to how dynsyms are loaded.

**Comment by yglukhov** [comment]
Closing this for now. Please reopen if you think it can be fixed in nimx.

**Comment by NookSF** [comment]
OK, not counting ios, that module is OpenGL only. We'd need something like:

https://github.com/nimious/gles

**Comment by yglukhov** [comment]
I can't see how Nim's opengl is not compatible with gles. Nimx compiles and runs on iOS and Android without any problems.

**Comment by NookSF** [comment]
Yeah, that's what I meant - no Linux `EGL/GLES` support. The module knows about `libGL.so` but not `libGLES.so`.
