### ISSUE TITLE
Can not compile example

### ISSUE THREAD

**Issue by luntik2012** [yglukhov/nimx#21]
# File: main.nim
import nimx.sdl_window
import nimx.text_field

# First create a window. Window is the root of view hierarchy.
# Currently there are two types of windows. SdlWindow should be used
# with native targets, JSCanvasWindow should be used for WebGL target
var wnd : SdlWindow
wnd.new()
wnd.init(newRect(40, 40, 800, 600))

# Create a static text field and add it to view hierarchy
let label = newLabel(newRect(20, 20, 150, 20))
label.text = "Hello, world!"
wnd.addSubview(label)

# Run the main loop
runUntilQuit()

I run this:
nim c -r --noMain main.nim

And get this:
/home/nick/.nimble/pkgs/nimx-0.1/nimx/sdl_window.nim(78, 87) Error: undeclared identifier: 'SDL_WINDOW_ALLOW_HIGHDPI'

**Comment by yglukhov** [comment]
Please update your sdl2:
```sh
nimble install sdl2
```

**Comment by luntik2012** [comment]
Thank you
