### ISSUE TITLE
image.nim(594, 17) Error: undeclared field: 'statusCode'

### ISSUE THREAD

**Issue by retsyo** [yglukhov/nimx#218]
I am using MSYS2+MingW64 on Win7 64 bits.  But `$ ./nim  c -r --noMain  --threads:on /e/prg/nim/my_code/test_nimx.nim` says ```.nimble\pkgs\nimx-0.1\nimx\image.nim(594, 17) Error: undeclared field: 'statusCode'```

the test_nimx.nim is just your demo
```nim
# File: main.nim
import nimx.window
import nimx.text_field
import nimx.system_logger # Required because of Nim bug (#4433)

proc startApp() =
    # First create a window. Window is the root of view hierarchy.
    var wnd = newWindow(newRect(40, 40, 800, 600))

    # Create a static text field and add it to view hierarchy
    let label = newLabel(newRect(20, 20, 150, 20))
    label.text = "Hello, world!"
    wnd.addSubview(label)

# Run the app
runApplication:
    startApp()
```

**Comment by yglukhov** [comment]
Please make sure you have the latest `async_http_request` package.
```sh
nimble install -y https://github.com/yglukhov/async_http_request
```

**Comment by retsyo** [comment]
I have deleted all the pkg, and `./nimble install nimx` takes a long time to run. However, `./nim c -r --noMain --threads:on /e/prg/nim/my_code/test_nimx.nim` says
```nim
C:\Users\USR\.nimble\pkgs\nimx-0.1\nimx\composition.nim(233, 17) template/generic instantiation from here
C:\Users\USR\.nimble\pkgs\nimsl-0.2\nimsl\nimsl.nim(23, 49) Error: cannot generate code for: I


```

**Comment by yglukhov** [comment]
Thats a Nim bug, which is fixed by https://github.com/nim-lang/Nim/pull/5677. Until then nim version `0ccbc8234` seems to work for me.

**Comment by yglukhov** [comment]
Should work with latest nim devel now. Please reopen if it doesn't.

**Comment by retsyo** [comment]
Yes, the new nim can compile your above example code. However, the `-d:release` produces an `1,385,784` bytes EXE file which needs SDL2.dll (`1,069,136` bytes). Is this whole app some big?

**Comment by yglukhov** [comment]
I'm afraid so. Most of the size in the sample comes from `stb_image` loading code. Getting rid of SDL2 dependency is in the plans. Probably image loading could also utilize whatever native API is available, but that is not in the nearest plans.

**Comment by retsyo** [comment]
So, is there a way to tell nimx do static link with SDL2 on the command line?

**Comment by yglukhov** [comment]
I don't think so. But you can make a PR ;)

**Comment by retsyo** [comment]
It is hard for me to make a PR :(

**Comment by yglukhov** [comment]
@retsyo, there's another (better) way. If you are a winapi geek, you could greatly help by removing sdl dependency altogether for windows =). Basically, you would need to add a new file `nimx.private.windows.winapi_window.nim` that does what other `*window.nim` files do, but using winapi. Patch `timers.nim` and `perform_on_main_thread.nim` to use winapi. As you can see, all of the work to be done is event handling and window/context creation.
