### ISSUE TITLE
Example Freezes

### ISSUE THREAD

**Issue by TomAshley303** [yglukhov/nimx#236]
I run the example in the README and I get: http://storage3.static.itmages.com/i/17/0620/h_1497922783_2406791_1132230b22.png

**Comment by yglukhov** [comment]
@TomAshley303, judging from the screenshot, it's a mix of macos and linux environment? Could you please elaborate on your configuration? Can you please confirm that other SDL2 software works properly in your environment?

**Comment by TomAshley303** [comment]
It's Ubuntu. Just running the example from the readme. idk about SDL2. I'm running KDE5/plasma.

**Comment by TomAshley303** [comment]
This continues to happen. I'm on a different version of Linux now (KDE Neon) which is Ubuntu 16.04 with KDE 5.10.4. If I resize the window, it displays as normal until it looses focus in which case the focused window contents get frozen onto the nimx window. This is a fresh install. To get nimx to work, I installed the libsdl2-2.0-0 package and ran `ln -s /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 /usr/lib/x86_64-linux-gnu/libSDL2.so`.

**Comment by yglukhov** [comment]
@TomAshley303 i've never seen such behavior with nimx, and have no idea how to fix it. I would suspect either hardware or specific software environment problem. So you're on your own here for now. As a start I would recommend you write a small sdl program in c and see how it works in your case.

**Comment by Jipok** [comment]
I have a similar problem with example from readme.  Just minimize and then maximize the window.
![image](https://user-images.githubusercontent.com/25588359/28793590-e61013ae-764c-11e7-80c4-4b6d92ec0401.jpg)
Asus laptop with Intel Core i3 4010U
OS: Manjaro 17.0.2
Linux 4.12.3-1
DE: xfce4 4.12.4-1

**Comment by Jipok** [comment]
Tested in another environment. 
Cinnamon 3.4.3-1. Works without problems.
Openbox 3.6.1-3. Same as in xfce4.

**Comment by yglukhov** [comment]
Could you please retest with latest #253 fix?

**Comment by yglukhov** [comment]
Please reopen if still reproduces.
