### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by matkuki** [yglukhov/nimx#245]
Trying to compile sample01_welcome.nim throws:
```
...\.nimble\pkgs\nimx-0.1\nimx\assets\web_url_handler.nim(77, 17) Error: undeclared field: 'statusCode'
```

Windows Vista x64
Nim: devel-0.17.1 with mingw (x86)

**Comment by yglukhov** [comment]
Looks like `async_http_request` is outdated.
```
nimble install -y https://github.com/yglukhov/async_http_request
```

**Comment by matkuki** [comment]
Thanks @yglukhov ,
but now I get:
...\.nimble\pkgs\nimx-0.1\nimx\view_event_handling.nim(8, 8) Error: method is not a base

Any ideas?

**Comment by yglukhov** [comment]
@matkuki, try compiling the `main.nim` from samples. AFAIR, compiling individual sample files doesn't work for some reason.

**Comment by matkuki** [comment]
Tried compiling ```main.nim```, now the error is:
```
....nimble\pkgs\nimx-0.1\nimx\cursor.nim(70, 42) Error: undeclared identifier: 'SystemCursor'
```

**Comment by yglukhov** [comment]
That's coming from old sdl2 i suppose.
```
nimble install -y sdl2
```

**Comment by matkuki** [comment]
Great! That did it!
Thanks @yglukhov
