### ISSUE TITLE
view_event_handling.nim(8, 8) Error: method is not a base

### ISSUE THREAD

**Issue by obchain** [yglukhov/nimx#251]
compile in windows with this error
nim version 0.17 compiled with
nim c -r --threads:on main.nim for the usage demo.

**Comment by yglukhov** [comment]
Please clarify, what version of nim you are using and the command you compile with.

**Comment by obchain** [comment]
@yglukhov

**Comment by yglukhov** [comment]
@obchain, please try with latest devel.

**Comment by yglukhov** [comment]
Please reopen if still an issue.
