### ISSUE TITLE
Image render issues on Mac OSX

### ISSUE THREAD

**Issue by floydnunez** [yglukhov/nimx#261]
I have an app that shows some images. On Mac OS X Sierra it displays them with some artifacts on the borders. On Windows it is displayed correctly. Haven't tried other platforms.

https://www.dropbox.com/s/ns7jjxpzeap04ph/NimxProblemDemo.zip?dl=0

I made a demo project; I made a simple circle with borders that have no transparencies. The Mac version fuzzes the borders and adds a line on the bottom and right side. Some other images add lines on the borders.

This is the circle
<img width="138" alt="circle" src="https://user-images.githubusercontent.com/1719570/30385217-e4bae5f4-987c-11e7-8487-97b116f1c3cd.png">

This is the Windows 10 version
![how_it_looks_in_windows](https://user-images.githubusercontent.com/1719570/30385238-f37d3c40-987c-11e7-97eb-16fdc1752577.png)

This is the Mac version
<img width="634" alt="how_it_looks_on_mac" src="https://user-images.githubusercontent.com/1719570/30385248-faeee78a-987c-11e7-99a0-5663b4229077.png">

My code is very simple

proc startApp() =
    # First create a window. Window is the root of view hierarchy.
    var wnd = newWindow(newRect(40, 40, 600, 480)) 

    let image = imageWithContentsOfFile("circle.png");
    let iv = newImageView(newRect(100, 100, 400, 400), image, ImageFillRule.NoFill )
    wnd.addSubview(iv)

runApplication:
   startApp()

Any ideas?

**Comment by yglukhov** [comment]
Should be fixed, please retest.

**Comment by floydnunez** [comment]
Ah I tested it! it works perfectly, thanks you very much.
