### ISSUE TITLE
value out of range: -2 [RangeError]

### ISSUE THREAD

**Issue by alehander42** [yglukhov/nimx#268]
I get this error when I try to run the example. I have libSDL2 installed on Ubuntu 16.10, it's working fine with the js target

**Comment by yglukhov** [comment]
Any stack trace?

**Comment by alehander42** [comment]
```nim
Traceback (most recent call last)
x.nim(3)                 x
system.nim(2730)         sysFatal
Error: unhandled exception: value out of range: -2 [RangeError]
```

I have `libSDL2-2.0.so.0` installed (I had a problem with that initially, I am not sure if this error is connect)

**Comment by yglukhov** [comment]
Hmm, still not much (
Please provide the source code, your nim version, the command you're compiling with.

**Comment by yglukhov** [comment]
I suppose this has been fixed a while ago. Please reopen if still an issue.
