### ISSUE TITLE
Running main_nimx.exe in Windows

### ISSUE THREAD

**Issue by andrewgohlk** [yglukhov/nimx#272]
Hi,
Why when I double clicked to run the main_nimx.exe  in Windows, it always launches a terminal window beside the main graphic window?
Any way to prevent the launching of the terminal window?

**Comment by Yardanico** [comment]
@andrewgohlk add "--app:gui" to your compilation command
Can be closed?

**Comment by andrewgohlk** [comment]
Great program. Thanks for the quick response. 

Perhaps should addv this tip in the example.
Also, to have an 'examples' directory with sample codes demonstrating the features of nimx.
This will make newbies easier to learn.
