### ISSUE TITLE
Getting started with nimx

### ISSUE THREAD

**Issue by thumperus** [yglukhov/nimx#292]
I've been checking out nim and needed a gui. Nimx looked like a good fit so I thought I'd try it. I got the test application running okay and built a couple of very basic applications from the readme and one other small example. However, I'm unable to really connect how it all works with layouts and such. The six example is too small and the full demonstratio application is too much for me to put the pieces together. Is there a resource you would recommend for getting started with nimx other than the full test/example application?

**Comment by yglukhov** [comment]
Added some initial docs.
https://github.com/yglukhov/nimx/tree/master/doc
What do you think?

**Comment by thumperus** [comment]
I haven't had a chance to experiment or dive into it more just yet, but it looks promising. Especially the outline that indicates there is more to come. Thank you for adding this.
