### ISSUE TITLE
Cannot build tests on Mac OS X

### ISSUE THREAD

**Issue by Peter2121** [yglukhov/nimx#320]
Trying to follow the procedure _Running nimx samples_ to build tests, I get an error from XCode:

```
MacBook-Pro-de-Peter:test peter$ /Users/peter/.nimble/bin/nake 
No task specified, running default task defined by nakefile.
Build settings from command line:
    SDKROOT = macosx10.13
    SYMROOT = build

xcodebuild: error: 'Xcode/SDL/SDL.xcodeproj' does not exist.
MacBook-Pro-de-Peter:test peter$ pwd
/Users/peter/.nimble/pkgs/nimx-0.1/test
```

**Comment by Peter2121** [comment]
Sorry, I did not see the requirement - SDL2 (it would be nice to put it to the README.md of the project).
I can go one step ahead, but there is still an error during the build:
`/Users/peter/.nimble/pkgs/variant-0.2.7/variant.nim(66, 46) Error: undeclared identifier: 'nnkTupleConstr'`

**Comment by Peter2121** [comment]
The same error trying to build `helloworld.nim`

**Comment by yglukhov** [comment]
Can you try with the latest nim devel please?

**Comment by yglukhov** [comment]
Fixed in variant. Please update.
```
nimble install -y variant
```

**Comment by Peter2121** [comment]
I cannot install the Git version:
`lib/pure/future.nim(2, 15) Error: list of key:value pairs expected`
...after `./koch tools` (following the web site procedure)
The version I use is 0.18.0, installed using `brew`
