### ISSUE TITLE
Variant: undeclared identifier: 'nnkTupleConstr'

### ISSUE THREAD

**Issue by logc** [yglukhov/nimx#321]
Trying to compile the example provided in the README, I get an error from the `variant` library.
```
/variant-0.2.7/variant.nim(66, 46) Error: undeclared identifier: 'nnkTupleConstr'
```
Since you also provide that library, I wanted to make you aware about the error here because I don't know if it is an error in the library or on how `nimx` uses it.

**Comment by yglukhov** [comment]
Fixed in variant. Please update.
```
nimble install -y variant
```
