### ISSUE TITLE
code sample in readme shows blank window until it's moved to another monitor or resized

### ISSUE THREAD

**Issue by timotheecour** [yglukhov/nimx#331]
when launching app:

![image](https://user-images.githubusercontent.com/2194784/46781458-9c2c0b80-ccd6-11e8-8ba8-7e220255e455.png)

after moving to another monitor 
EDIT or resizing

![image](https://user-images.githubusercontent.com/2194784/46781476-ab12be00-ccd6-11e8-9f1f-a96771f89563.png)

this happens everytime i try.

on a single monitor it just gives blank window. EDIT: resizing should problably also fix it

i'm on OSX mojave. Same issue with both normal mode or mojave dark mode.

## EDIT
this also happens when creating new windows from an existing window, eg: using the test app in `tests/`, after clicking on, for eg, table in split view, the window newly created will be all blank
![image](https://user-images.githubusercontent.com/2194784/46795002-e70d4980-ccfd-11e8-8288-4c51e8693738.png)

## workaround
resize window (manually)

**Comment by yglukhov** [comment]
I suppose that's an SDL issue. Which version are you using. Can you try with 2.0.8?

**Comment by timotheecour** [comment]
I already am using it:
/Users/timothee/homebrew/opt/sdl2/bin/sdl2-config --version
2.0.8

**Comment by Tormund** [comment]
Same issue with 2.0.9.

**Comment by yglukhov** [comment]
Should be fixed. Please retest with latest nimx and sdl 2.0.10.
