### ISSUE TITLE
`nake`: /Users/timothee/git_clone/nim/nimx/nimx/naketools.nim(6, 41) Error: cannot open file: closure_compiler

### ISSUE THREAD

**Issue by timotheecour** [yglukhov/nimx#332]
nimble path closure_compiler
/Users/timothee/.nimble/pkgs/closure_compiler-0.3.4

nake
/Users/timothee/git_clone/nim/nimx/nimx/naketools.nim(6, 41) Error: cannot open file: closure_compiler

tree /Users/timothee/.nimble/pkgs/closure_compiler-0.3.4
/Users/timothee/.nimble/pkgs/closure_compiler-0.3.4
├── closure_compiler
├── closure_compiler.nimble
├── compiler-latest
│   ├── COPYING
│   ├── README.md
│   └── compiler.jar
└── nimblemeta.json

## EDIT
for some reason the culprit seems to be that something (not me ;-) ) removed `closure_compiler.nim` ; perhaps during installation process of nimx via `nimble install` after a clone

## workaround
re-run nake after
`nimble develop closure_compiler` somewhere

**Comment by yglukhov** [comment]
I can't reproduce it with latest nimble.

**Comment by yglukhov** [comment]
@timotheecour, can you confirm that this happens when installing nimx in an empty environment?

**Comment by timotheecour** [comment]
tried in an empty environment via:
```
mv ~/.nimble ~/.nimble.bak1
export PATH=$nimc_D/bin:$PATH # to that nimble points to devel-built nimble
nimble install nimx
```
I cannot reproduce the issue; maybe it got fix with a recent update of nimble, or maybe it was smthg else; closing

**Comment by timotheecour** [comment]
re-opening , this happened again; something is removing `closure_compiler` I just don't know what or how to reproduce it

**Comment by timotheecour** [comment]
i noticed my `closure_compiler` was in a detached state (caused by a bug of nimble that was already fixed); rebuilt closure_compiler properly, will re-open if the bug pops up again
