### ISSUE TITLE
README example Error: node lacks field: intVal

### ISSUE THREAD

**Issue by iffy** [yglukhov/nimx#336]
I'm trying to run the README example on macOS Sierra 10.12.6 and get this error:

```
stack trace: (most recent call last)
../../../.nimble/pkgs/nimsl-0.3/nimsl/nimsl.nim(14) getGLSLFragmentShader
../../../.nimble/pkgs/nimsl-0.3/nimsl/nimsl.nim(8) getShaderCode
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(318) genProcDef
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(384) gen
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(118) genStmtList
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(385) gen
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(180) genCall
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(391) gen
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(245) genSym
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(393) gen
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(318) genProcDef
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(384) gen
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(118) genStmtList
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(386) gen
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(195) genInfixCall
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(178) genCall
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(147) genSystemCall
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(398) gen
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(399) gen
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(349) genBracketExpr
../../../.nimble/pkgs/nimx-0.1/nimx/context.nim(251, 46) template/generic instantiation of `newCompositionWithNimsl` from here
../../../.nimble/pkgs/nimx-0.1/nimx/composition.nim(345, 41) template/generic instantiation of `getGLSLFragmentShader` from here
../../../.nimble/pkgs/nimsl-0.3/nimsl/private/glsl_codegen.nim(349, 24) Error: node lacks field: intVal
```

**Comment by timotheecour** [comment]
had that; after `nimble develop nimsl` somewhere I get instead:

nake
No task specified, running default task defined by nakefile.
Hint: used config file '/Users/timothee/git_clone/nim/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim/nim.cfg' [Conf]
Hint: used config file '/Users/timothee/.config/nim/config.nims' [Conf]
/Users/timothee/.config/nim/config.nims [config.nims used]
/Users/timothee/git_clone/nim/nimx/test/main.nim(2, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/nimx/test/sample_registry.nim(2, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/nimx/nimx/view.nim(3, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/nimx/nimx/context.nim(5, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/nimx/nimx/font.nim(6, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/nimx/nimx/private/font/stb_ttf_glyph_provider.nim(5, 1) template/generic instantiation from here
/Users/timothee/.nimble/pkgs/ttf-0.2.8/ttf.nim(588, 19) Error: invalid pragma: unchecked

**Comment by yglukhov** [comment]
Fixed in nimsl, please update it.
