### ISSUE TITLE
I'd really like to use nimx but I can't get it to work

### ISSUE THREAD

**Issue by iffy** [yglukhov/nimx#339]
I've been really excited about nimx and the possibility of writing cross-platform apps but I haven't yet been able to get it to run with the latest version of Nim.  #336

I've started a module for making auto-updating, cross-platform apps using Nim.  The goal is to make something as nice to use (and with similar features) as Electron:  https://github.com/iffy/wiish  I'd really rather use the excellent work you've already done with nimx instead of trying to redo it, but I can't tell from the README   And I can't tell what packaging features nimx already provides.

Could you provide a working example of these (if they're already part of nimx -- I'm not asking for new features, just new documentation):

- Building an iOS app
- Running an iOS app on the simulator
- Building an Android app
- Running an Android app on the emulator
- Building a macOS app
- Building a Windows app
- Building a Linux app

I'd be happy to contribute PRs to this repo for documentation or even features -- I just don't really know what works/doesn't.

**Comment by yglukhov** [comment]
Does this help? https://github.com/yglukhov/nimx/blob/master/doc/building-for-different-platforms.md

**Comment by iffy** [comment]
Okay, if I use clone and do `nimble develop` for `jester`, `closure_compiler`, `httpbeast`, `nimsl`, `nake` and `nimx` then that works.
