### ISSUE TITLE
nake droid fails, invalid AndroidManifest.xml

### ISSUE THREAD

**Issue by sillibird** [yglukhov/nimx#354]
When building anything for android with nake, the gradlew build always fails with

```sh
A problem occurred configuring root project 'com.mycompany.NimxApp'.
> org.xml.sax.SAXParseException; systemId: file:/.../build/android/com.mycompany.NimxApp/src/main/AndroidManifest.xml; lineNumber: 14; columnNumber: 19; Element type "activity" must be followed by either attribute specifications, ">" or "/>".
```

**Comment by Tormund** [comment]
Can you attach manifest here?

**Comment by sillibird** [comment]
AndroidManifest.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="$(PACKAGE_ID)"
    android:versionCode="$(BUILD_NUMBER)"
    android:versionName="$(APP_VERSION)" >

    <application android:label="@string/app_name"
                 android:hardwareAccelerated="true"
                 android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
                 >
        <activity android:name="$(ACTIVITY_CLASS_NAME)"
                  android:label="@string/app_name"
                  android:configChanges="keyboardHidden|orientation|screenSize"
                  $(SCREEN_ORIENTATION)
                  >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
```

**Comment by Tormund** [comment]
Try this:
1. `nimble install -y ` or `nimble develop -y` at nimx folder - naketools.nim used from installed nimx package
2. Delete executable nakefile (.exe at windows) and build folder.
3. Re run `nake droid`

**Comment by Tormund** [comment]
Ok, please provide nimx, nim hahses and which sdl version used.

**Comment by Tormund** [comment]
Use `nim --version` - for nim and `git rev-parse HEAD`  for nimx.
Also make sure you have only 1 nimx version installed in ~/.nimple/pkgs. 
You can just delete all nimx folders from pkgs and reinstall with nimble.

**Comment by sillibird** [comment]
nim: `7beea1642ddf7845a9a0034c7a93ccbe15894c36`

As for nimx, I cant actually get `git rev-parse HEAD` to work, because theres no .git folder in any of the nimx directories?

**Comment by Tormund** [comment]
Ok, you can find revision at ~/.nimble/pkgs/nimx*/nimblemeta.json, field vcsRevision

**Comment by Tormund** [comment]
I have same revisions and all works. Removing of build folder should help.

**Comment by sillibird** [comment]
I've tried many different combinations (removing build folder, reinstall nimx/SDL), and always produce the same results.

**Comment by yglukhov** [comment]
What platform are you using? Is this still the issue?

**Comment by yglukhov** [comment]
Make sure to set SDL_NOME env var to the **source code** of sdl, which can be downloaded from the official site. I've improved the error in naketools.nim.
