### ISSUE TITLE
does not compile on netbsd

### ISSUE THREAD

**Issue by devosalain** [yglukhov/nimx#359]
ld: cannot find -lSDL2
Even if SDL2 lib is installed.

**Comment by Infernion** [comment]
Same issue on Windows

**Comment by yglukhov** [comment]
Pretty sure there's something wrong with your sdl2 setup. Feel free to reopen if the following works for you but nimx doesn't:
```
echo "void main(){}" > test.c
gcc -lSDL2 test.c
```
