### ISSUE TITLE
Proper Nim Import Statements For Nimx? 

### ISSUE THREAD

**Issue by topcheese** [yglukhov/nimx#386]
Hi, nice project you've put together.  It doesn't compile on a Mac using this format for import 
```
import nimx / [ view, segmented_control, color_picker, button, image, image_view,
                text_field, slider, popup_button, progress_indicator ]
```
The fields that cause it to fail are "popup_button, text_field, color_picker."  It will compile if I use **import nimx/text_field** format.   What's the difference and perhaps the more complex imports needs to be refactored?
~Thanks!
Edit: oops I'm sure you want to know the error.  It complained about missing some x86_64 symbols with using this format.

**Comment by topcheese** [comment]
The problem is in the order of the format.  The examples fail if you don't load nimx/window first.

**Comment by topcheese** [comment]
Some of the examples compile successfully but fail to display anything.  I think it may have something to do with the import statements.  I will spend a little more time today to look at it.

**Comment by yglukhov** [comment]
Indeed the samples are supposed to be run through main.nim. But your problem "missing some x86_64 symbols" is something different, maybe nimcache got messed up somehow.
