### ISSUE TITLE
[Question] How can I embed an OpenGL window

### ISSUE THREAD

**Issue by mantielero** [yglukhov/nimx#417]
First, I am not that experienced. How could I embed an openGL window?

I m thinking about inserting a window from [gr framework](https://gr-framework.org/about.html).

Something like [this](https://gr-framework.org/tutorials/gr3_wx.html).

**Comment by yglukhov** [comment]
To integrate something that draws to current opengl context into nimx, you just subclass a View, and override `method draw`. Here's a sample of integrating nanovg into nimx: https://github.com/yglukhov/nimx_nanovg/blob/master/main.nim
