### ISSUE TITLE
[Question] How does the AssetManaget work?

### ISSUE THREAD

**Issue by mantielero** [yglukhov/nimx#435]
Could you explain how the asset manager work? 

I am trying to show an image using the full path, but I am failing (unless I put the image in the `res` folder).

Regard
Jose M.

**Comment by yglukhov** [comment]
Asset manager is used to retrieve assets from the app resources, which are different things depending on your platform (on windows and linux this is `res` folder). To load an image from an arbitrary file path use `imageWithContentsOfFile`. To load image from arbitrary URL (including `http://`, `https://`, `file://`) use `loadImageFromURL`

**Comment by mantielero** [comment]
Thanks a lot. I managed to use `imageWithContentsOfFile`. I don't know why `loadImageFromURL` is not working for me. I am using similar code to your sample 3. Something like the following:
```nim
method init*(v: ImageSampleView, r: Rect) =
    procCall v.View.init(r)
    loadImageFromURL("file:///home/jose/src/pdf/Frances_01.pdf_FOLDER/original_thumbnails_256/68db24e7-fe4f-407b-89af-04bbbc7746f9-16.png") do(i: Image):
        v.httpImage = i
        v.setNeedsDisplay()

    #do(i: Image, err: string):
    v.image =  imageWithContentsOfFile("/home/jose/src/pdf/Frances_01.pdf_FOLDER/original_thumbnails_256/68db24e7-fe4f-407b-89af-04bbbc7746f9-16.png")
    v.setNeedsDisplay()
```
but `b.httpImage` is empty, and I don't know why.

**Comment by yglukhov** [comment]
Ah, turns out `imageWithContentsOfFile` doesn't support `file:` scheme. PRs are welcome :)

**Comment by yglukhov** [comment]
The question is answered i suppose

**Comment by mantielero** [comment]
Yes it is. Thanks a lot mate.
