### ISSUE TITLE
\.nimble\pkgs\nimx-0.1\nimx\layout_vars.nim(19, 32) Error: type mismatch: got <Variable>

### ISSUE THREAD

**Issue by jlp765** [yglukhov/nimx#454]
but expected one of:
proc newExpression(constant: float = 0): Expression
  first type mismatch at position: 1
  required type for constant: float
  but expression 'left(phs)' is of type: Variable
proc newExpression(term: Term; constant: float = 0): Expression
  first type mismatch at position: 1
  required type for term: Term
  but expression 'left(phs)' is of type: Variable
proc newExpression(terms: seq[Term]; constant: float = 0): Expression
  first type mismatch at position: 1
  required type for terms: seq[Term]
  but expression 'left(phs)' is of type: Variable

expression: newExpression(left(phs))

----------------------
On a win10
with nim version; Nim Compiler Version 1.4.2 [Windows: amd64]

**Comment by yglukhov** [comment]
Try updating `kiwi` dependency
```
nimble install -y kiwi
```

**Comment by jlp765** [comment]
Yes, that fixed it thanks.
