### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by WilliamBehrens** [yglukhov/nimx#466]
Is there plans on adding Wayland support to the Linux build? as far as I can tell at least  Nimx still relies on Xorg which is slowing getting outdated as more window managers and desktops switch over.

**Comment by yglukhov** [comment]
Nimx should support wayland, and it's a bug if it doesn't. Currently this comes with sdl2, which I'm willing to get rid of eventually, but yeah, wayland is one of important targets.
