### ISSUE TITLE
Can't compile with -d:ssl for Android; Please help.

### ISSUE THREAD

**Issue by alexisad** [yglukhov/nimx#475]
ld: error: undefined symbol: glob
  >>> referenced by stdlib_net.nim.c:1415 (build\android\com.mycompany.NimxApp\nimcache\arm64-v8a\stdlib_net.nim.c:1415)
  >>>               stdlib_net.nim.c.o:(newContext__p45vOS9b3iK2JJ1Y7aIJ9bUA) in archive C:/Users/sadovoy/Documents/nimapps/ksk-clean/build/android/com.mycompany.NimxApp/jni/main/arm64-v8a/libmain_static.a
  >>> referenced by stdlib_net.nim.c:1590 (build\android\com.mycompany.NimxApp\nimcache\arm64-v8a\stdlib_net.nim.c:1590)
  >>>               stdlib_net.nim.c.o:(newContext__p45vOS9b3iK2JJ1Y7aIJ9bUA) in archive C:/Users/sadovoy/Documents/nimapps/ksk-clean/build/android/com.mycompany.NimxApp/jni/main/arm64-v8a/libmain_static.a

  ld: error: undefined symbol: globfree
  >>> referenced by stdlib_net.nim.c:1478 (build\android\com.mycompany.NimxApp\nimcache\arm64-v8a\stdlib_net.nim.c:1478)
  >>>               stdlib_net.nim.c.o:(newContext__p45vOS9b3iK2JJ1Y7aIJ9bUA) in archive C:/Users/sadovoy/Documents/nimapps/ksk-clean/build/android/com.mycompany.NimxApp/jni/main/arm64-v8a/libmain_static.a
  >>> referenced by stdlib_net.nim.c:1502 (build\android\com.mycompany.NimxApp\nimcache\arm64-v8a\stdlib_net.nim.c:1502)
  >>>               stdlib_net.nim.c.o:(newContext__p45vOS9b3iK2JJ1Y7aIJ9bUA) in archive C:/Users/sadovoy/Documents/nimapps/ksk-clean/build/android/com.mycompany.NimxApp/jni/main/arm64-v8a/libmain_static.a
  >>> referenced by stdlib_net.nim.c:1653 (build\android\com.mycompany.NimxApp\nimcache\arm64-v8a\stdlib_net.nim.c:1653)
  >>>               stdlib_net.nim.c.o:(newContext__p45vOS9b3iK2JJ1Y7aIJ9bUA) in archive C:/Users/sadovoy/Documents/nimapps/ksk-clean/build/android/com.mycompany.NimxApp/jni/main/arm64-v8a/libmain_static.a
  >>> referenced 1 more times
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  make: *** [C:/Users/sadovoy/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/build-binary.mk:728: C:/Users/sadovoy/Documents/nimapps/ksk-clean/build/android/com.mycompany.NimxApp/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/libmain.so] Error 1

**Comment by yglukhov** [comment]
Use `-d:nimDisableCertificateValidation` but obviously you'll get no validation. Also you'll have to provide your own libssl/libcrypto.
