### ISSUE TITLE
Readme example failing to compile on Win 64 bit (bad format: SDL2.dll)

### ISSUE THREAD

**Issue by gcaplan** [yglukhov/nimx#486]
Hi

Fresh install of Nim and nimx on a Win 10 Pro 64 bit workstation.

nimx installed via $nimble install. There were some warnings during installation.

Compiling the Readme example with the Readme flags failed with the error:

```
PS D:\Google Drive\Nim\code\sandbox> nim c -r --threads:on gui.nim
Hint: used config file 'c:\Users\user\AppData\Local\Programs\nim-1.4.8\config\nim.cfg' [Conf]      
Hint: used config file 'c:\Users\user\AppData\Local\Programs\nim-1.4.8\config\config.nims' [Conf]                                                                                                   im
Hint: 7870 lines; 0.058s; 7MiB peakmem; Debug build; proj: D:\Google Drive\Nim\code\sandbox\gui.nim; out: D:\Google Drive\Nim\code\sandbox\gui.exe [SuccessX]
Hint: "D:\Google Drive\Nim\code\sandbox\gui.exe"  [Exec]
could not load: SDL2.dll
(bad format; library may be wrong architecture)
```

**Comment by yglukhov** [comment]
It's either your nim is in 32bit mode, and SDL2.dll is 64bit or the other way around. Make sure architectures match.

**Comment by gcaplan** [comment]
My bad - I was distracted by the Defender security warning during download and hit the wrong button, it seems.

Sorry for the false report.

**Comment by LazyGamer1111** [comment]
how did you change it?
