### ISSUE TITLE
Access to Mixer

### ISSUE THREAD

**Issue by wwderw** [yglukhov/nimx#492]
I've been looking around and I didn't see anywhere where there was access to the mixer for sound.  Is there a way to get sound or is there a helper library for that that works well with nimx?  I could use nimraylib just for the audio, but don't know how well it well take not having access to window controls etc.

Thanks

**Comment by yglukhov** [comment]
Sound is out of scope of nimx. I believe there's a lot of options, one being [sound](https://github.com/yglukhov/sound).
