### ISSUE TITLE
Set Window Icon

### ISSUE THREAD

**Issue by wwderw** [yglukhov/nimx#494]
Is it possible to set the window icon?  I looked through the nim files that dealt with windowing (at least the ones that looked obvious to me, so I could have missed it), but I couldn't find anything that dealt with icon setting.

Reason for it, as it is just a finishing touch for an app/game.

Thanks for the help.

**Comment by yglukhov** [comment]
There's no such api in nimx, but it should be possible to get native window handle and do it in a platform-specific way. Also PRs are welcome.
