### ISSUE TITLE
Directory window widget

### ISSUE THREAD

**Issue by nixfreak** [yglukhov/nimx#507]
Does nimX have a way to show a directory structure , for instance a box that shows your PWD or a path that you can browse to? 

I'm looking for a gui that allows me to pull up a directory and then edit files using a bash script that relates to adding extended attributes on a linux file system. 

```$ zenity --file-selection --multiple --filename "${HOME}/"```

https://linuxconfig.org/how-to-use-graphical-widgets-in-bash-scripts-with-zenity

**Comment by yglukhov** [comment]
No, but have a look at [os_files](https://github.com/Tormund/os_files) and [nim-native-dialogs](https://github.com/SSPkrolik/nim-native-dialogs). There's also [dialogs](https://github.com/nim-lang/dialogs), but it seems to use gtk on macos instead of AppKit, whereas the former two use AppKit.
