### ISSUE TITLE
trying to run tests

### ISSUE THREAD

**Issue by darkoverlordofdata** [yglukhov/nimx#51]
When I follow these instructions:
cd $(nimble path nimx)/test
nake # Build and run on the current platform

I get a permission denied error. I changed the permissions on the test/nakefile, and now I get this error, and it just hangs, and I have to kill the terminal session from the system monitor:

`home/bruce/.nimble/pkgs/nimx-0.1/nimx/sdl_perform_on_main_thread.nim(6, 5) Warning: Cannot prove that 'evt' is initialized. This will become a compile time error in the future. [ProveInit]
`
I'm on elementary OS 0.3.2 Freya (64-bit), Built on Ubuntu 14.04

**Comment by darkoverlordofdata** [comment]
So, I am able to get the small demo shown in the usage section of the readme to work. I am satisfied that the library is installed and working.

**Comment by yglukhov** [comment]
@darkoverlordofdata, is there anything wrong in the lib that you couldnt run it at first?

**Comment by yglukhov** [comment]
Closing this meanwhile. Please report if anything could be improved/fixed.
