### ISSUE TITLE
livedemo in Brave browser is broken

### ISSUE THREAD

**Issue by veksha** [yglukhov/nimx#519]
https://yglukhov.github.io/nimx/livedemo/main.html

![image](https://github.com/yglukhov/nimx/assets/275333/f88026bd-b428-42f9-a272-16e8d2d3922d)

os: windows11
browser: Brave nightly

**Comment by niutech** [comment]
Click Brave Shields button and disable fingerprinting protection.

**Comment by veksha** [comment]
thanks. i'm no longer using brave browser.
