### ISSUE TITLE
Install fails due to missing dependency "darwin"

### ISSUE THREAD

**Issue by DestyNova** [yglukhov/nimx#522]
I've tried installing nimx with Nim 1.6.12 and 2.0.0, and it errors out in the same place due to a dependency on the package `darwin` which can't be found. Maybe it was removed from the Nimble package repo?

```
...
Downloading https://github.com/yglukhov/plists using git
  Verifying dependencies for plists@0.2.0
    Reading official package list
   Checking for darwin@any version
 Installing darwin@any version
    Reading official package list
    Prompt: darwin not found in any local packages.json, check internet for updated packages? [y/N]
y
    Answer: Downloading official package list
     Trying http://google.com
   Warning: Downloaded packages.json file is invalid, discarding.
     Trying http://google.com/404
   Warning: Could not download: 404 Not Found
     Trying http://irclogs.nim-lang.org/packages.json
     Trying http://nim-lang.org/nimble/packages.json
    Success Package list downloaded.
    Reading official package list
     Error: Package not found.
```

Is there a way to skip this dependency since the name "darwin" indicates something specific to Mac OS X, which I don't need?

**Comment by yglukhov** [comment]
> Maybe it was removed from the Nimble package repo?

I'm pretty sure [it's there](https://github.com/nim-lang/packages/blob/e52b18948feb1cca13ada322218aa19d03ef4fd4/packages.json#L19341C3-L19353). Might be some problem with your nim/nimble installation? In any case this is better reported in the nimble repo.

> Is there a way to skip this dependency since the name "darwin" indicates something specific to Mac OS X, which I don't need?

You could just clone nimx locally, patch its nimble file accordingly and `nimble install` from within the directory.

**Comment by DestyNova** [comment]
> > Maybe it was removed from the Nimble package repo?
> 
> I'm pretty sure [it's there](https://github.com/nim-lang/packages/blob/e52b18948feb1cca13ada322218aa19d03ef4fd4/packages.json#L19341C3-L19353). Might be some problem with your nim/nimble installation? In any case this is better reported in the nimble repo.

Thanks for that pointer. It's there in the Git blob, but not on the [published version](https://nim-lang.org/nimble/packages.json) it seems.

> > Is there a way to skip this dependency since the name "darwin" indicates something specific to Mac OS X, which I don't need?
> 
> You could just clone nimx locally, patch its nimble file accordingly and `nimble install` from within the directory.

Good to know :+1:
