### ISSUE TITLE
nake fails into endless loop when SDL2.dll is not found on Windows

### ISSUE THREAD

**Issue by SSPkrolik** [yglukhov/nimx#54]

**Comment by shawnye** [comment]
+1

I download SDL2.dll from http://cn.dll-files.com/sdl2.dll.html
32bit 2.0.4.0,

when running exe ,error happened: 
<pre>
D:\WORKSPACE\nim\test\src>test_gui
start gui...
Traceback (most recent call last)
test_gui.nim(8)          test_gui
sdl_window.nim(103)      :anonymous
sdl_window.nim(100)      newSdlWindow
view.nim(42)             init
sdl_window.nim(92)       init
sdl_window.nim(68)       initCommon
opengl.nim(110)          newGraphicsContext
opengl.nim(87)           glGetProc
dynlib.nim(35)           raiseInvalidLibrary
Error: unhandled exception: could not find symbol: glGenFramebuffers [LibraryErr
or]
</pre>

**Comment by yglukhov** [comment]
@shawnye your problem is likely in opengl lib, not sdl. Make sure you have decent video drivers and opengl version. Cant say for sure as i don't use windows.

**Comment by SSPkrolik** [comment]
The problem disappeared :)
